repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.72.1
    hooks:
      - id: terraform_docs
      - id: terraform_fmt

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.46.2
    hooks:
      - id: golangci-lint
        entry: golangci-lint run --fix
        types: [go]
        language: golang
        pass_filenames: false
